### PR TITLE
Fix panic trying to get a param value

### PR DESCRIPTION
**Pull request by imikushin**
This should fix the panic reported by rancher/os#624

### CODE REVIEW

**Comment by imikushin** [comment]
@ibuildthecloud take a look

**Comment by ibuildthecloud** [comment]
I'm more a fan of go-check, just FYI.  I know we use testify in other places.

**Comment by ibuildthecloud** [comment]
@imikushin can you just explain the basic problem?  Like what was the code doing before that blew up.  Just not obvious to me what the real change is here since a method moved.  I'm not sure I see that change.

**Comment by imikushin** [comment]
The problem was in trying to get `parts[2]` (the _3rd_ element) when there are only 2 elements in `parts`

**Pull request merged**
